//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORIZACION_REPORTES_CREDITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTORIZACION_REPORTES_CREDITO()
        {
            this.FIRMA_TESTIGOS = new HashSet<FIRMA_TESTIGOS>();
        }
    
        public int id_autorizacion_persona_fisica { get; set; }
        public int id_credito { get; set; }
        public Nullable<System.DateTime> fecha_autoriza_consulta { get; set; }
        public Nullable<System.DateTime> fecha_recibe_consulta { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> telefono_cliente { get; set; }
        public string registro_federal { get; set; }
        public Nullable<System.DateTime> fecha_consultaenBC_CC1 { get; set; }
        public string folio_consultaenBC_CC1 { get; set; }
        public string folio_consultaenBC_CC2 { get; set; }
        public Nullable<System.DateTime> fecha_consultaenBC_CC2 { get; set; }
        public Nullable<System.DateTime> fecha_consultaenBC_CC3 { get; set; }
        public string folio_consultaenBC_CC3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIRMA_TESTIGOS> FIRMA_TESTIGOS { get; set; }
    }
}
