//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTA_BIENES_MUEBLES
    {
        public int id_bienes_muebles { get; set; }
        public int id_carta { get; set; }
        public string descripcion { get; set; }
        public string folio { get; set; }
        public string vehiculo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<System.DateTime> ann { get; set; }
        public Nullable<byte> ann_prenda { get; set; }
        public string color_prenda { get; set; }
        public string uso_prenda { get; set; }
        public string estado_prenda { get; set; }
        public Nullable<decimal> valor_compra_actual { get; set; }
        public Nullable<decimal> valor_actual_compra { get; set; }
        public string numero_serie { get; set; }
        public string nombre_cliente { get; set; }
        public string lugar_cliente { get; set; }
        public Nullable<System.DateTime> fecha_cliente { get; set; }
        public string firma_cliente { get; set; }
        public string nombre_responsable { get; set; }
        public string lugar_responsable { get; set; }
        public Nullable<System.DateTime> fecha_responsable { get; set; }
        public string firma_responsable { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual CARTAS CARTAS { get; set; }
    }
}
