//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHECK_LIST()
        {
            this.CONTENIDO_CHECK = new HashSet<CONTENIDO_CHECK>();
        }
    
        public int id_check_list { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_asesor { get; set; }
        public string codigo_operacion { get; set; }
        public Nullable<short> secuencia { get; set; }
        public Nullable<decimal> monto_solicitado { get; set; }
        public string tipo_garantia { get; set; }
        public Nullable<System.DateTime> fecha_validacion_checklist { get; set; }
        public Nullable<byte> numero_integrantes { get; set; }
        public string tipo_check_list { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENIDO_CHECK> CONTENIDO_CHECK { get; set; }
    }
}
