//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENIDO_CHECK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENIDO_CHECK()
        {
            this.COSTO_INSUMOS = new HashSet<COSTO_INSUMOS>();
            this.DECLARACION_INGRESOS = new HashSet<DECLARACION_INGRESOS>();
            this.EVALUACION_TECNICA = new HashSet<EVALUACION_TECNICA>();
            this.FLUJOS = new HashSet<FLUJOS>();
            this.INFORMACION_OPERATIVA_NEGOCIO = new HashSet<INFORMACION_OPERATIVA_NEGOCIO>();
            this.INFORMACION_PATRIMONIAL_BG = new HashSet<INFORMACION_PATRIMONIAL_BG>();
            this.INFORMACION_PATRIMONIAL = new HashSet<INFORMACION_PATRIMONIAL>();
            this.PLAN_CONSTRUCCION_SUMALE = new HashSet<PLAN_CONSTRUCCION_SUMALE>();
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
        }
    
        public int id_documento { get; set; }
        public Nullable<int> id_check_list { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> status_SI { get; set; }
        public Nullable<bool> status_na { get; set; }
        public Nullable<bool> status_carpeta_electronica { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<byte> seccion_pertenece { get; set; }
    
        public virtual CHECK_LIST CHECK_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COSTO_INSUMOS> COSTO_INSUMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_INGRESOS> DECLARACION_INGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUACION_TECNICA> EVALUACION_TECNICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLUJOS> FLUJOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_OPERATIVA_NEGOCIO> INFORMACION_OPERATIVA_NEGOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PATRIMONIAL_BG> INFORMACION_PATRIMONIAL_BG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PATRIMONIAL> INFORMACION_PATRIMONIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_CONSTRUCCION_SUMALE> PLAN_CONSTRUCCION_SUMALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
    }
}
