//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTO_INSUMOS
    {
        public int id { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string actividad_principal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string producto_insumo { get; set; }
        public string cantidad { get; set; }
        public string cantidad_unidad_medida { get; set; }
        public string costo_unitario { get; set; }
        public Nullable<decimal> costo_total { get; set; }
    
        public virtual CONTENIDO_CHECK CONTENIDO_CHECK { get; set; }
    }
}
