//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITO_PYME_EXTRA
    {
        public int id_extra { get; set; }
        public int id_credito_pyme { get; set; }
        public Nullable<byte> sector { get; set; }
        public string nombre { get; set; }
        public Nullable<byte> porcentaje { get; set; }
        public Nullable<decimal> valor_venta { get; set; }
        public string canales_distribucion { get; set; }
        public Nullable<byte> porcentaje_venta { get; set; }
        public string forma_pago { get; set; }
        public string plazos_credito { get; set; }
        public string nombre_cliente { get; set; }
        public string plazos_cliente { get; set; }
        public string nombre_producto { get; set; }
        public string ventaja_competitiva { get; set; }
        public string desventaja_competitiva { get; set; }
        public string capacidad_instalada { get; set; }
        public string unidades { get; set; }
        public string capacidad_utilizada { get; set; }
        public string capacidad_disponible { get; set; }
        public Nullable<int> sucursal { get; set; }
        public string tipo_cuenta { get; set; }
        public string funcionario { get; set; }
        public string telefono { get; set; }
        public string domicilio { get; set; }
        public string contacto { get; set; }
    
        public virtual CREDITO_PYME CREDITO_PYME { get; set; }
    }
}
