//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUADRO_INVERSION
    {
        public int id_destino { get; set; }
        public int id_expediente { get; set; }
        public string destino { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
    }
}
