//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_INGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DECLARACION_INGRESOS()
        {
            this.FIRMA_TESTIGOS = new HashSet<FIRMA_TESTIGOS>();
        }
    
        public int id_declaracion { get; set; }
        public int id_documento { get; set; }
        public int id_cliente { get; set; }
        public int id_sucursal { get; set; }
        public int id_grupo { get; set; }
        public Nullable<byte> secuencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string actividad_declarada { get; set; }
        public Nullable<decimal> ventas_semanales { get; set; }
        public Nullable<decimal> costo_ventas_semanal { get; set; }
        public Nullable<decimal> utilidad_bruta { get; set; }
        public Nullable<decimal> total_gasto_operativas { get; set; }
        public Nullable<decimal> utilidad_operativa { get; set; }
        public Nullable<decimal> gastos_familiares { get; set; }
        public Nullable<decimal> otros_ingresos { get; set; }
        public Nullable<decimal> pago_otras_deudas { get; set; }
        public Nullable<decimal> capacidad_pago { get; set; }
        public Nullable<decimal> cuota_semanal_pactada { get; set; }
        public Nullable<decimal> cobertura_cuota { get; set; }
        public Nullable<decimal> monto_solicitado { get; set; }
        public Nullable<decimal> caja_activo { get; set; }
        public Nullable<decimal> caja_pasivos { get; set; }
        public Nullable<decimal> inventario_activo { get; set; }
        public Nullable<decimal> inventario_pasivos { get; set; }
        public Nullable<decimal> total_activo { get; set; }
        public Nullable<decimal> total_pasivos { get; set; }
        public string observaciones { get; set; }
        public Nullable<decimal> pago_semana { get; set; }
    
        public virtual CONTENIDO_CHECK CONTENIDO_CHECK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIRMA_TESTIGOS> FIRMA_TESTIGOS { get; set; }
    }
}
