//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES
    {
        public int id_direccion { get; set; }
        public int id_documento { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public Nullable<int> pais_id { get; set; }
        public Nullable<int> colonia_id { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public Nullable<int> ciudad_id { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> cp_id { get; set; }
        public string localidad { get; set; }
        public string referencias { get; set; }
        public string tipo { get; set; }
    }
}
