//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACION_PRODUCTIVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVALUACION_PRODUCTIVA()
        {
            this.TIPO_PRODUCTIVO = new HashSet<TIPO_PRODUCTIVO>();
        }
    
        public int id_evaluacion_productiva { get; set; }
        public int id_documento { get; set; }
        public int id_cliente { get; set; }
        public string actividad_negocio { get; set; }
        public string situacion_agricola { get; set; }
        public Nullable<decimal> ingreso_venta1 { get; set; }
        public Nullable<decimal> ingreso_venta2 { get; set; }
        public Nullable<decimal> total_costos { get; set; }
        public Nullable<decimal> alimentacion_gf { get; set; }
        public Nullable<decimal> educacion_gf { get; set; }
        public Nullable<decimal> servicios_publicos_gf { get; set; }
        public Nullable<decimal> transporte_gf { get; set; }
        public Nullable<decimal> salud_gf { get; set; }
        public Nullable<decimal> celular_gf { get; set; }
        public Nullable<decimal> alquileres_gf { get; set; }
        public Nullable<decimal> gas_gf { get; set; }
        public Nullable<decimal> gastos_generales_familia { get; set; }
        public Nullable<decimal> otros_gastos { get; set; }
        public Nullable<decimal> total_gastos { get; set; }
        public Nullable<decimal> ventas_mensuales { get; set; }
        public Nullable<decimal> costo_venta_mensual { get; set; }
        public Nullable<decimal> gastos_operativos_mensuales { get; set; }
        public Nullable<decimal> gatsos_transporte_flete { get; set; }
        public Nullable<decimal> renta { get; set; }
        public Nullable<decimal> gastos_salarios { get; set; }
        public Nullable<decimal> servicios_publicos { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public Nullable<decimal> vehiculo { get; set; }
        public Nullable<decimal> otros_gastos_negocio { get; set; }
        public Nullable<decimal> total_gastos_negocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PRODUCTIVO> TIPO_PRODUCTIVO { get; set; }
    }
}
