//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPEDIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPEDIENTE()
        {
            this.ANEXO_EXPEDIENTE = new HashSet<ANEXO_EXPEDIENTE>();
            this.CUADRO_INVERSION = new HashSet<CUADRO_INVERSION>();
            this.FIRMA_TESTIGOS = new HashSet<FIRMA_TESTIGOS>();
        }
    
        public int id_expediente { get; set; }
        public int id_sucursal { get; set; }
        public int id_producto { get; set; }
        public int id_grupo { get; set; }
        public string codigo { get; set; }
        public string tipo_expediente { get; set; }
        public string nombre { get; set; }
        public Nullable<byte> edad { get; set; }
        public string estado_civil { get; set; }
        public string nombre_conyugue { get; set; }
        public string giro_negocio { get; set; }
        public string ubicacion_negocio { get; set; }
        public Nullable<byte> antiuguedad_negocio { get; set; }
        public string esquema { get; set; }
        public string hacienda { get; set; }
        public Nullable<byte> secuencia { get; set; }
        public Nullable<decimal> monto_credito_anterior { get; set; }
        public string procedencia_competencia { get; set; }
        public Nullable<byte> numero_integrantes { get; set; }
        public string creditos_adicionales { get; set; }
        public Nullable<byte> tasa_anterior { get; set; }
        public Nullable<decimal> credito_vigente_actual { get; set; }
        public Nullable<decimal> monto_solicitado_propuesto { get; set; }
        public Nullable<byte> tasa_interes { get; set; }
        public string plazo_propuesto { get; set; }
        public string indicadores_monto { get; set; }
        public string seccion2_1 { get; set; }
        public string seccion2_2 { get; set; }
        public string seccion2_3 { get; set; }
        public string seccion2_4 { get; set; }
        public string seccion2_5 { get; set; }
        public string seccion3_1 { get; set; }
        public string seccion3_2 { get; set; }
        public string seccion3_3 { get; set; }
        public string seccion3_4 { get; set; }
        public string seccion3_5 { get; set; }
        public string seccion3_6 { get; set; }
        public string seccion4_1 { get; set; }
        public string seccion4_2 { get; set; }
        public string seccion4_3 { get; set; }
        public string seccion4_4 { get; set; }
        public string seccion4_5 { get; set; }
        public string seccion5_1 { get; set; }
        public string seccion5_2_1 { get; set; }
        public string seccion5_2_2 { get; set; }
        public string seccion6_1 { get; set; }
        public string seccion6_2 { get; set; }
        public string seccion6_3 { get; set; }
        public string seccion6_4 { get; set; }
        public string seccion6_5 { get; set; }
        public string seccion6_6 { get; set; }
        public string seccion7_1 { get; set; }
        public string seccion7_2 { get; set; }
        public string seccion7_3 { get; set; }
        public string seccion7_4 { get; set; }
        public string seccion7_5 { get; set; }
        public string seccion7_6 { get; set; }
        public string seccion7_7 { get; set; }
        public string seccion7_8 { get; set; }
        public string seccion7_9 { get; set; }
        public string seccion7_10 { get; set; }
        public string seccion8_1 { get; set; }
        public string seccion8_2 { get; set; }
        public string seccion9_1 { get; set; }
        public string seccion9_2 { get; set; }
        public string seccion10_1 { get; set; }
        public string seccion10_2 { get; set; }
        public string seccion10_3 { get; set; }
        public string seccion10_4 { get; set; }
        public string seccion10_5 { get; set; }
        public string anexo_1 { get; set; }
        public string respuesta_manifiesto1 { get; set; }
        public string respuesta_manifiesto2 { get; set; }
        public string anexo2 { get; set; }
        public string nombre_anexo { get; set; }
        public string numero_anexo { get; set; }
        public string nombre_representante_legal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANEXO_EXPEDIENTE> ANEXO_EXPEDIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUADRO_INVERSION> CUADRO_INVERSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIRMA_TESTIGOS> FIRMA_TESTIGOS { get; set; }
    }
}
