//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FICHAS()
        {
            this.REFERENCIAS = new HashSet<REFERENCIAS>();
        }
    
        public int id_ficha { get; set; }
        public int id_cliente { get; set; }
        public int id_documento { get; set; }
        public string tipo_documento { get; set; }
        public string tipo_ficha { get; set; }
        public Nullable<System.DateTime> fecha_levantamiento { get; set; }
        public Nullable<System.DateTime> fecha_constitucion { get; set; }
        public string nombre_comercial { get; set; }
        public string nombre_cliente { get; set; }
        public string app_cliente { get; set; }
        public string apm_cliente { get; set; }
        public string clave_elector { get; set; }
        public string curp { get; set; }
        public string rfc { get; set; }
        public string numero_serie_fiel { get; set; }
        public string nacionalidad { get; set; }
        public string pais_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string estado_civil { get; set; }
        public string estado_nacimiento { get; set; }
        public string sexo { get; set; }
        public string deps_economicos { get; set; }
        public string escolaridad { get; set; }
        public Nullable<byte> ann_estudio { get; set; }
        public string actividad { get; set; }
        public string profesion { get; set; }
        public string ocupacion { get; set; }
        public string lenguaje { get; set; }
        public string rol_cliente { get; set; }
        public Nullable<bool> discapacidad { get; set; }
        public Nullable<bool> uso_internet { get; set; }
        public string redes_sociales { get; set; }
        public string tipo_casa { get; set; }
        public string telefono_fijo { get; set; }
        public string correo_electronico { get; set; }
        public Nullable<bool> apoyo_social { get; set; }
        public string nombre_adicional { get; set; }
        public string app_adicional { get; set; }
        public string apm_adicional { get; set; }
        public string conocido_pareja { get; set; }
        public string conocido_por { get; set; }
        public Nullable<int> estado_nacimiento_adicional { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_adicional { get; set; }
        public string ocupacion_adicional { get; set; }
        public string lugar_trabajo_adicional { get; set; }
        public string clave_elector_adicional { get; set; }
        public string escolaridad_adicional { get; set; }
        public string ann_estudio_adicional { get; set; }
        public string rol_adicional { get; set; }
        public Nullable<byte> porcentaje_adicional { get; set; }
        public string direccion_adicional { get; set; }
        public string referencia_localizacion_adicional { get; set; }
        public string tipo_casa_adicional { get; set; }
        public string telefono_adicional { get; set; }
        public string actividad_e { get; set; }
        public string negocio { get; set; }
        public string sector { get; set; }
        public Nullable<byte> ano_oficio { get; set; }
        public string tipo_negocio { get; set; }
        public string referencia_localizacion { get; set; }
        public string ubicacion_negocio { get; set; }
        public string telefono_negocio { get; set; }
        public string tipo_local { get; set; }
        public string dias_trabajo { get; set; }
        public string dias_descanso { get; set; }
        public string horario { get; set; }
        public Nullable<byte> numero_trabajadores { get; set; }
        public string otros_ingresos { get; set; }
        public Nullable<byte> antiguedad_actividad { get; set; }
        public Nullable<byte> antiguedad_domicilio { get; set; }
        public string cuenta_sucursales { get; set; }
        public string capacidad_pago { get; set; }
        public string cobertura_cuota { get; set; }
        public string nombre_aval_empresa { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_trabajo { get; set; }
        public string telefono_empresa { get; set; }
        public string dia_trabajo_empresa { get; set; }
        public string dias_descanso_empresa { get; set; }
        public string puesto { get; set; }
        public Nullable<decimal> sueldo_mensual { get; set; }
        public Nullable<decimal> gastos_familiares { get; set; }
        public Nullable<decimal> disponible_mensual { get; set; }
        public Nullable<decimal> otros_ingresos_empresa { get; set; }
        public string avenida_acceso { get; set; }
        public string lineas_transporte { get; set; }
        public string calles_principales { get; set; }
        public string tiempo_aprox { get; set; }
        public string lat_negocio { get; set; }
        public string lon_negocio { get; set; }
        public string lat_domicilio { get; set; }
        public string lon_domicilio { get; set; }
        public Nullable<bool> respuesta_croquis1 { get; set; }
        public Nullable<bool> respuesta_croquis2 { get; set; }
        public Nullable<bool> respuesta_manifiesto { get; set; }
        public Nullable<bool> respuesta_accionista { get; set; }
        public Nullable<byte> porcentaje_accionista { get; set; }
        public Nullable<bool> respuesta_manifiesto2 { get; set; }
        public Nullable<bool> respuesta_manifiesto3 { get; set; }
        public string redes_sociales2 { get; set; }
        public string medio_enterado { get; set; }
        public string nombre_beneficiario { get; set; }
        public string app_beneficiario { get; set; }
        public string apm_beneficiario { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_beneficiario { get; set; }
        public string telefono_beneficiario { get; set; }
        public string parentesco_beneficiario { get; set; }
        public Nullable<byte> participacion_beneficiario { get; set; }
        public string sexo_beneficiario { get; set; }
        public string casa_beneficiario { get; set; }
        public string nombre_tercero { get; set; }
        public string app_tercero { get; set; }
        public string apm_tercero { get; set; }
        public string codigo_familia { get; set; }
        public string referencia_localizacion_actividad { get; set; }
        public string referencia_localizacion_bene { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERENCIAS> REFERENCIAS { get; set; }
    }
}
