//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMA_TESTIGOS
    {
        public int id_testigos { get; set; }
        public int id_documento { get; set; }
        public string nombre { get; set; }
        public string app { get; set; }
        public string apm { get; set; }
        public string firma { get; set; }
        public string cargo { get; set; }
    
        public virtual ACTA_INTEGRACION_COMITE ACTA_INTEGRACION_COMITE { get; set; }
        public virtual AUTORIZACION_REPORTES_CREDITO AUTORIZACION_REPORTES_CREDITO { get; set; }
        public virtual DECLARACION_INGRESOS DECLARACION_INGRESOS { get; set; }
        public virtual EVALUACION_TECNICA EVALUACION_TECNICA { get; set; }
        public virtual EXPEDIENTE EXPEDIENTE { get; set; }
        public virtual FLUJOS FLUJOS { get; set; }
    }
}
