//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJOS_TIPOS
    {
        public int id { get; set; }
        public int id_flujo { get; set; }
        public string tipo_flujo { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual FLUJOS FLUJOS { get; set; }
    }
}
