//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTOS_OPERATIVOS_NEGOCIO
    {
        public int id { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_evaluacion_economica_simple { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual INFORMACION_OPERATIVA_NEGOCIO INFORMACION_OPERATIVA_NEGOCIO { get; set; }
    }
}
