//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_CREDITICIO_CLIENTE
    {
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> CuotaMensual { get; set; }
        public Nullable<decimal> incrementoMonto { get; set; }
        public Nullable<decimal> incrementoCuota { get; set; }
        public Nullable<decimal> disponobleMaximoreportadoporcliente { get; set; }
        public Nullable<decimal> utilidadOperativa { get; set; }
        public Nullable<decimal> capDePagoMensual { get; set; }
        public Nullable<decimal> coberturadeCuota { get; set; }
        public int id { get; set; }
        public int plazo { get; set; }
    }
}
