//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_PATRIMONIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFORMACION_PATRIMONIAL()
        {
            this.PATRIMONIO_ACTIVO_BIENES = new HashSet<PATRIMONIO_ACTIVO_BIENES>();
            this.PATRIMONIO_INVENTARIO = new HashSet<PATRIMONIO_INVENTARIO>();
        }
    
        public int id_patrimonial { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string ocupacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<byte> secuencia { get; set; }
        public string tipo_doc { get; set; }
        public Nullable<decimal> total_inventario { get; set; }
        public Nullable<decimal> sub_total_bienes_activo { get; set; }
        public Nullable<decimal> sub_total_bienes_pasivo { get; set; }
        public Nullable<decimal> total_activos { get; set; }
        public Nullable<decimal> total_pasivos { get; set; }
        public Nullable<decimal> total_patrimonio { get; set; }
        public Nullable<decimal> subtotal_costo_produccion { get; set; }
        public Nullable<decimal> gran_total_costo_produccion { get; set; }
        public Nullable<decimal> gran_total_aportaciones { get; set; }
        public Nullable<decimal> gran_total_recursos { get; set; }
        public Nullable<decimal> nivel_maximo_endeudamientos_aportacion { get; set; }
    
        public virtual CONTENIDO_CHECK CONTENIDO_CHECK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO_ACTIVO_BIENES> PATRIMONIO_ACTIVO_BIENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO_INVENTARIO> PATRIMONIO_INVENTARIO { get; set; }
    }
}
