//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_OPERATIVA_DETALLADA
    {
        public int id { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_asesor { get; set; }
        public Nullable<int> id_dinamica_ventas_compras_diarias { get; set; }
        public Nullable<int> id_total_ventas_compras { get; set; }
        public Nullable<int> id_gastos_operativos { get; set; }
        public Nullable<int> id_gastos_familia { get; set; }
        public string sector_economico { get; set; }
        public string actividad_especifica { get; set; }
        public Nullable<int> numero_evaluacion { get; set; }
        public Nullable<int> secuencia_base { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto_solicitar { get; set; }
        public Nullable<decimal> ultimo_monto_operado { get; set; }
        public Nullable<decimal> venta_semanal_alta { get; set; }
        public Nullable<decimal> venta_semanal_baja { get; set; }
        public Nullable<decimal> venta_mensual_alta { get; set; }
        public Nullable<decimal> venta_mensual_baja { get; set; }
        public Nullable<decimal> venta_semanal_lunes { get; set; }
        public Nullable<bool> venta_semanal_alta_Lunes { get; set; }
        public Nullable<bool> venta_semanal_baja_Lunes { get; set; }
        public Nullable<decimal> venta_Semanal_martes { get; set; }
        public Nullable<bool> venta_semanal_alta_martes { get; set; }
        public Nullable<bool> venta_semanal_baja_martes { get; set; }
        public Nullable<decimal> venta_semanal_miercoles { get; set; }
        public Nullable<bool> venta_semanal_alta_miercoles { get; set; }
        public Nullable<bool> venta_semanal_baja_miercoles { get; set; }
        public Nullable<decimal> venta_Semanal__jueves { get; set; }
        public Nullable<bool> venta_semanal_alta_jueves { get; set; }
        public Nullable<bool> venta_semanal_baja_jueves { get; set; }
        public Nullable<decimal> venta_semanal_viernes { get; set; }
        public Nullable<bool> venta_semanal_alta_viernes { get; set; }
        public Nullable<bool> venta_semanal_baja_viernes { get; set; }
        public Nullable<decimal> venta_semanal_sabado { get; set; }
        public Nullable<bool> venta_semanal_alta_sabado { get; set; }
        public Nullable<bool> ventasemanalbaja_sabado { get; set; }
        public Nullable<decimal> venta_semanal_domingo { get; set; }
        public Nullable<bool> venta_semanal_alta_domingo { get; set; }
        public Nullable<bool> venta_semanal_baja_domingo { get; set; }
        public Nullable<decimal> semanal { get; set; }
        public Nullable<decimal> venta_mensual_enero { get; set; }
        public Nullable<decimal> venta_mensual_febrero { get; set; }
        public Nullable<decimal> venta_mensual_marzo { get; set; }
        public Nullable<decimal> venta_mensual_abril { get; set; }
        public Nullable<decimal> venta_mensual_mayo { get; set; }
        public Nullable<decimal> venta_mensual_junio { get; set; }
        public Nullable<decimal> venta_mensual_julio { get; set; }
        public Nullable<decimal> venta_mensual_agosto { get; set; }
        public Nullable<decimal> venta_mensual_septimebre { get; set; }
        public Nullable<decimal> venta_mensual_octubre { get; set; }
        public Nullable<decimal> venta_mensual_noviembre { get; set; }
        public Nullable<decimal> venta_mensual_diciembre { get; set; }
        public Nullable<decimal> utilidad_bruta_negocio_capital { get; set; }
        public Nullable<decimal> utilidad_bruta_negocio_porcentual { get; set; }
        public Nullable<decimal> utilidad_operativa_negocio_capital { get; set; }
        public Nullable<decimal> utilidad_operativa_negocio_porcentual { get; set; }
        public Nullable<decimal> ingresos_negocio { get; set; }
        public Nullable<decimal> otros_ingresos_cliente { get; set; }
        public Nullable<decimal> aportaciones_familiar_comprobables { get; set; }
        public Nullable<decimal> ingresos_totales { get; set; }
        public Nullable<decimal> gastos_familia { get; set; }
        public Nullable<decimal> suma_cuotas_deudas_otras_microfinancieras { get; set; }
        public Nullable<decimal> cuotas_deudas_acreedores_diversos { get; set; }
        public Nullable<decimal> pago_mensual_portandas { get; set; }
        public Nullable<decimal> egresos_totales { get; set; }
        public Nullable<decimal> disponible_mensual_maximo_reportado_cliente { get; set; }
        public Nullable<decimal> capacidad_pago { get; set; }
        public Nullable<decimal> gastos_operativos_negocio_total { get; set; }
        public Nullable<decimal> gastos_familia_total { get; set; }
    }
}
