//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_PATRIMONIAL_BG
    {
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_asesor { get; set; }
        public Nullable<int> id_documentos { get; set; }
        public string Sectoreconomico { get; set; }
        public string EspecifiqueActividad { get; set; }
        public Nullable<byte> Nodeevaluación { get; set; }
        public Nullable<byte> Nodesecuencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> Otrasinstitucionesdecreditoyoagiotistas_CuotaMensual { get; set; }
        public Nullable<decimal> Cuotasdecreditosdiversos_CuotaMensual { get; set; }
        public Nullable<decimal> Pagomensualportandas_CuotaMensual { get; set; }
        public Nullable<decimal> Cuentasporpagaraproveedores_CuotaMensual { get; set; }
        public Nullable<decimal> Pagosanticipadosdeclientes_CuotaMensual { get; set; }
        public Nullable<decimal> Otrasinstitucionesdecreditoyoagiotistas_TotalDeuda { get; set; }
        public Nullable<decimal> Cuotasdecreditosdiversos_TotalDeuda { get; set; }
        public Nullable<decimal> Pagomensualportandas_TotalDeuda { get; set; }
        public Nullable<decimal> Cuentasporpagaraproveedores_TotalDeuda { get; set; }
        public Nullable<decimal> Pagosanticipadosdeclientes_TotalDeuda { get; set; }
        public Nullable<int> Otrasinstitucionesdecreditoyoagiotistas_CuotasMenusualesFaltantes { get; set; }
        public Nullable<int> Cuotasdecreditosdiversos_CuotasMenusualesFaltantes { get; set; }
        public Nullable<int> Pagomensualportandas_CuotasMenusualesFaltantes { get; set; }
        public Nullable<int> Cuentasporpagaraproveedores_CuotasMenusualesFaltantes { get; set; }
        public Nullable<int> Pagosanticipadosdeclientes_CuotasMenusualesFaltantes { get; set; }
        public Nullable<decimal> TotalCuotaMensual_cuentasporpagar { get; set; }
        public Nullable<decimal> TotalDeuda_cuentasporpagar { get; set; }
        public Nullable<decimal> Deudoresdiversos_CuotaMensual { get; set; }
        public Nullable<decimal> Tandasporrecibir_CuotaMensual { get; set; }
        public Nullable<decimal> Pagosanticipadosaproveeedores_CuotaMensual { get; set; }
        public Nullable<decimal> Cuentasporcobraraclientes_CuotaMensual { get; set; }
        public Nullable<decimal> Deudoresdiversos_TotalDeuda { get; set; }
        public Nullable<decimal> Tandasporrecibir_TotalDeuda { get; set; }
        public Nullable<decimal> Pagosanticipadosaproveeedores_TotalDeuda { get; set; }
        public Nullable<decimal> Cuentasporcobraraclientes_TotalDeuda { get; set; }
        public Nullable<int> Deudoresdiversos_CuotasFaltantes { get; set; }
        public Nullable<int> Tandasporrecibir_CuotasFaltantes { get; set; }
        public Nullable<int> Pagosanticipadosaproveeedores_CuotasFaltantes { get; set; }
        public Nullable<int> Cuentasporcobraraclientes_CuotasFaltantes { get; set; }
        public Nullable<decimal> TotalCuotaMensual_cuentasporcobrar { get; set; }
        public Nullable<decimal> TotalDeuda_cuentasporcobrar { get; set; }
        public Nullable<decimal> CajaoEfectivo_Derechos { get; set; }
        public Nullable<decimal> AhorroBancos_Derechos { get; set; }
        public Nullable<decimal> Inventarios_Derechos { get; set; }
        public Nullable<decimal> ClientesProveedores_Derechos { get; set; }
        public Nullable<decimal> Deudoresyacreedoresdiversos_Derechos { get; set; }
        public Nullable<decimal> Deudastotal_Derechos { get; set; }
        public Nullable<decimal> Tandas_Derechos { get; set; }
        public Nullable<decimal> SUBTOTAL_Derechos { get; set; }
        public Nullable<decimal> CajaoEfectivo_Obligaciones { get; set; }
        public Nullable<decimal> AhorroBancos_Obligaciones { get; set; }
        public Nullable<decimal> Inventarios_Obligaciones { get; set; }
        public Nullable<decimal> ClientesProveedores_Obligaciones { get; set; }
        public Nullable<decimal> Deudoresyacreedoresdiversos_Obligaciones { get; set; }
        public Nullable<decimal> Deudastotal_Obligaciones { get; set; }
        public Nullable<decimal> Tandas_Obligaciones { get; set; }
        public Nullable<decimal> SUBTOTAL_Obligaciones { get; set; }
        public Nullable<decimal> Estanteramobiliarioherramienta_activo { get; set; }
        public Nullable<decimal> Maquinariayequipo_activo { get; set; }
        public Nullable<decimal> Vehiculos_activo { get; set; }
        public Nullable<decimal> LocalValor_activo { get; set; }
        public Nullable<decimal> Otrosmobiliarioequipodeoficinaycomputo_activo { get; set; }
        public Nullable<decimal> Estanteramobiliarioherramienta_pasivo { get; set; }
        public Nullable<decimal> Maquinariayequipo_pasivo { get; set; }
        public Nullable<decimal> Vehiculos_pasivo { get; set; }
        public Nullable<decimal> LocalValor_pasivo { get; set; }
        public Nullable<decimal> Otrosmobiliarioequipodeoficinaycomputo_pasivo { get; set; }
        public Nullable<decimal> SUBTOTAL_Bienesactivo { get; set; }
        public Nullable<decimal> SUBTOTAL_Bienespasivo { get; set; }
        public Nullable<decimal> Casas_derechos { get; set; }
        public Nullable<decimal> Terrenos_derechos { get; set; }
        public Nullable<decimal> Vehículos_derechos { get; set; }
        public Nullable<decimal> Otros_derechos { get; set; }
        public Nullable<decimal> SUBTOTAL_BienesPropiosderechos { get; set; }
        public Nullable<decimal> Casas_obligaciones { get; set; }
        public Nullable<decimal> Terrenos_obligaciones { get; set; }
        public Nullable<decimal> Vehículos_obligaciones { get; set; }
        public Nullable<decimal> Otros_obligaciones { get; set; }
        public Nullable<decimal> SUBTOTAL_BienesPropiosobligaciones { get; set; }
        public Nullable<decimal> SUBTOTALABC_Activo { get; set; }
        public Nullable<decimal> SUBTOTALABC_Pasivo { get; set; }
        public Nullable<decimal> Patrimonio { get; set; }
        public string ComentariosGenerales { get; set; }
    
        public virtual CONTENIDO_CHECK CONTENIDO_CHECK { get; set; }
    }
}
