//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CEAEntities : DbContext
    {
        public DB_CEAEntities()
            : base("name=DB_CEAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ACTA_INTEGRACION_COMITE> ACTA_INTEGRACION_COMITE { get; set; }
        public virtual DbSet<AdminBitacora> AdminBitacora { get; set; }
        public virtual DbSet<ANEXO_EXPEDIENTE> ANEXO_EXPEDIENTE { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AUTORIZACION_REPORTES_CREDITO> AUTORIZACION_REPORTES_CREDITO { get; set; }
        public virtual DbSet<CalificaciondeGrupoSolidario_Preguntas> CalificaciondeGrupoSolidario_Preguntas { get; set; }
        public virtual DbSet<CalificaciondeGrupoSolidario_Respuestas> CalificaciondeGrupoSolidario_Respuestas { get; set; }
        public virtual DbSet<CARTA_BIENES_MUEBLES> CARTA_BIENES_MUEBLES { get; set; }
        public virtual DbSet<CARTAS> CARTAS { get; set; }
        public virtual DbSet<CHECK_LIST> CHECK_LIST { get; set; }
        public virtual DbSet<CHECK_LIST_NOTARIA> CHECK_LIST_NOTARIA { get; set; }
        public virtual DbSet<CONTENIDO_CHECK> CONTENIDO_CHECK { get; set; }
        public virtual DbSet<COSTO_INSUMOS> COSTO_INSUMOS { get; set; }
        public virtual DbSet<CREDITO_PYME> CREDITO_PYME { get; set; }
        public virtual DbSet<CREDITO_PYME_EXTRA> CREDITO_PYME_EXTRA { get; set; }
        public virtual DbSet<CUADRO_INVERSION> CUADRO_INVERSION { get; set; }
        public virtual DbSet<DECLARACION_INGRESOS> DECLARACION_INGRESOS { get; set; }
        public virtual DbSet<DINAMICA_VENTAS_COMPRAS> DINAMICA_VENTAS_COMPRAS { get; set; }
        public virtual DbSet<DIRECCIONES> DIRECCIONES { get; set; }
        public virtual DbSet<EVALUACION_ECONOMICA_CLIENTE_EMPRENDEDOR> EVALUACION_ECONOMICA_CLIENTE_EMPRENDEDOR { get; set; }
        public virtual DbSet<EVALUACION_ECONOMICA_SIMPLE> EVALUACION_ECONOMICA_SIMPLE { get; set; }
        public virtual DbSet<EVALUACION_PRODUCTIVA> EVALUACION_PRODUCTIVA { get; set; }
        public virtual DbSet<EVALUACION_TECNICA> EVALUACION_TECNICA { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalNuevo> EvaluacionCualitativadeGrupoComunalNuevo { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalNuevo_Preguntas> EvaluacionCualitativadeGrupoComunalNuevo_Preguntas { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalNuevo_RESPUESTA_FORMULARIO> EvaluacionCualitativadeGrupoComunalNuevo_RESPUESTA_FORMULARIO { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalNuevo_Respuestas> EvaluacionCualitativadeGrupoComunalNuevo_Respuestas { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalSecuencial> EvaluacionCualitativadeGrupoComunalSecuencial { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalSecuencial_Preguntas> EvaluacionCualitativadeGrupoComunalSecuencial_Preguntas { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalSecuencial_Respuestas> EvaluacionCualitativadeGrupoComunalSecuencial_Respuestas { get; set; }
        public virtual DbSet<EXPEDIENTE> EXPEDIENTE { get; set; }
        public virtual DbSet<FICHAS> FICHAS { get; set; }
        public virtual DbSet<FIRMA_TESTIGOS> FIRMA_TESTIGOS { get; set; }
        public virtual DbSet<FLUJOS> FLUJOS { get; set; }
        public virtual DbSet<FLUJOS_TIPOS> FLUJOS_TIPOS { get; set; }
        public virtual DbSet<GASTOS_FAMILIA> GASTOS_FAMILIA { get; set; }
        public virtual DbSet<GASTOS_OPERATIVOS_NEGOCIO> GASTOS_OPERATIVOS_NEGOCIO { get; set; }
        public virtual DbSet<HISTORIAL_CREDITICIO_CLIENTE> HISTORIAL_CREDITICIO_CLIENTE { get; set; }
        public virtual DbSet<INFORMACION_OPERATIVA_DETALLADA> INFORMACION_OPERATIVA_DETALLADA { get; set; }
        public virtual DbSet<INFORMACION_OPERATIVA_NEGOCIO> INFORMACION_OPERATIVA_NEGOCIO { get; set; }
        public virtual DbSet<INFORMACION_PATRIMONIAL> INFORMACION_PATRIMONIAL { get; set; }
        public virtual DbSet<INFORMACION_PATRIMONIAL_BG> INFORMACION_PATRIMONIAL_BG { get; set; }
        public virtual DbSet<Insumos_Productos> Insumos_Productos { get; set; }
        public virtual DbSet<PATRIMONIO_ACTIVO_BIENES> PATRIMONIO_ACTIVO_BIENES { get; set; }
        public virtual DbSet<PATRIMONIO_INVENTARIO> PATRIMONIO_INVENTARIO { get; set; }
        public virtual DbSet<PLAN_CONSTRUCCION> PLAN_CONSTRUCCION { get; set; }
        public virtual DbSet<PLAN_CONSTRUCCION_SUMALE> PLAN_CONSTRUCCION_SUMALE { get; set; }
        public virtual DbSet<PROSPECTOS> PROSPECTOS { get; set; }
        public virtual DbSet<REFERENCIAS> REFERENCIAS { get; set; }
        public virtual DbSet<SCORING> SCORING { get; set; }
        public virtual DbSet<SCORING_PREGUNTAS> SCORING_PREGUNTAS { get; set; }
        public virtual DbSet<SCORING_RESPUESTA_FORMULARIO> SCORING_RESPUESTA_FORMULARIO { get; set; }
        public virtual DbSet<SCORING_RESPUESTAS> SCORING_RESPUESTAS { get; set; }
        public virtual DbSet<SITUACION_AGRICOLA> SITUACION_AGRICOLA { get; set; }
        public virtual DbSet<SOLICITUD_GRUPOS_CREDITO> SOLICITUD_GRUPOS_CREDITO { get; set; }
        public virtual DbSet<SOLICITUDES> SOLICITUDES { get; set; }
        public virtual DbSet<SUPERVISION_CLIENTE> SUPERVISION_CLIENTE { get; set; }
        public virtual DbSet<TIPO_PRODUCTIVO> TIPO_PRODUCTIVO { get; set; }
        public virtual DbSet<TOTAL_VENTAS_COMPRAS> TOTAL_VENTAS_COMPRAS { get; set; }
        public virtual DbSet<CalificaciondeGrupoSolidario_RESPUESTA_FORMULARIO> CalificaciondeGrupoSolidario_RESPUESTA_FORMULARIO { get; set; }
        public virtual DbSet<EvaluacionCualitativadeGrupoComunalSecuencial_RESPUESTA_FORMULARIO> EvaluacionCualitativadeGrupoComunalSecuencial_RESPUESTA_FORMULARIO { get; set; }
    }
}
