//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATRIMONIO_INVENTARIO
    {
        public int id_inventario { get; set; }
        public Nullable<int> id_patrimonio { get; set; }
        public string descripcion { get; set; }
        public string inventario_agropecuario { get; set; }
        public string unidad { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<float> cosecha { get; set; }
        public Nullable<byte> desarrollo { get; set; }
        public Nullable<decimal> total { get; set; }
        public string status { get; set; }
    
        public virtual INFORMACION_PATRIMONIAL INFORMACION_PATRIMONIAL { get; set; }
    }
}
