//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_CONSTRUCCION
    {
        public int id { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<decimal> mano_obra_material { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_total_mano_obra { get; set; }
    
        public virtual PLAN_CONSTRUCCION_SUMALE PLAN_CONSTRUCCION_SUMALE { get; set; }
    }
}
