//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_CONSTRUCCION_SUMALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAN_CONSTRUCCION_SUMALE()
        {
            this.PLAN_CONSTRUCCION = new HashSet<PLAN_CONSTRUCCION>();
        }
    
        public int id { get; set; }
        public int id_documento { get; set; }
        public int id_cliente { get; set; }
        public bool casa_propia { get; set; }
        public string nombre_propietario_vivienda_cliente { get; set; }
        public string tiempo_estimado_mejoramiento_vivienda { get; set; }
        public Nullable<decimal> valor_total_estimado_obra { get; set; }
        public Nullable<decimal> monto_total_solicitado { get; set; }
        public Nullable<System.DateTime> fecha_llenado { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public string descripcion_general_mejora_vivienda { get; set; }
        public string nombre_firma_solicitante { get; set; }
        public string nombre_firma_conyuge { get; set; }
        public string nombre_firma_gerentede_sucursal { get; set; }
        public string nombre_firma_asesor_credito { get; set; }
    
        public virtual CONTENIDO_CHECK CONTENIDO_CHECK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_CONSTRUCCION> PLAN_CONSTRUCCION { get; set; }
    }
}
