//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTOS
    {
        public int id_prospecto { get; set; }
        public Nullable<int> id_asesor { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string sucursal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombre { get; set; }
        public string app { get; set; }
        public string apm { get; set; }
        public string telefono { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public Nullable<int> colonia { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> municipio { get; set; }
        public Nullable<int> cp { get; set; }
        public string actividad_negocio { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string tipo_producto { get; set; }
        public Nullable<System.DateTime> fecha_visita_tentativa { get; set; }
        public string resolucion { get; set; }
        public string modo_enterado { get; set; }
        public Nullable<bool> status_prospecto { get; set; }
    }
}
