//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIAS
    {
        public int id_referencia { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public int id_ficha { get; set; }
        public string tipo_referencia { get; set; }
        public string nombre { get; set; }
        public string app { get; set; }
        public string apm { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string colonia { get; set; }
        public string relacion { get; set; }
        public string telefono { get; set; }
        public string pais_ref { get; set; }
        public Nullable<int> estado_ref { get; set; }
        public string tiempo_conocer { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual FICHAS FICHAS { get; set; }
    }
}
