//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORING
    {
        public int id_scoring { get; set; }
        public int id_check_list { get; set; }
        public int id_sucursal { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> calificacion { get; set; }
        public Nullable<byte> secuencia { get; set; }
        public Nullable<short> numero_evaluacion { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id_catalogo { get; set; }
    }
}
