//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_GRUPOS_CREDITO
    {
        public int id_grupo_credito { get; set; }
        public int id_solicitud { get; set; }
        public string tipo_credito { get; set; }
        public string codigo_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<short> secuencia { get; set; }
        public string tipo_transaccion { get; set; }
        public Nullable<short> numero_operaciones { get; set; }
        public Nullable<short> numero_estimado_operaciones { get; set; }
        public string nivel_riesgos_pld { get; set; }
        public Nullable<decimal> ingreso_semanal { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string actividad_economica { get; set; }
        public Nullable<decimal> monto_anterior { get; set; }
        public Nullable<decimal> monto_solicitado { get; set; }
        public Nullable<decimal> monto_autorizado { get; set; }
        public Nullable<short> status_modificacion { get; set; }
        public Nullable<decimal> monto_modificado { get; set; }
    
        public virtual SOLICITUDES SOLICITUDES { get; set; }
    }
}
