//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRODUCTIVO
    {
        public int id_tipo_productivo { get; set; }
        public Nullable<int> id_evaluacion_productiva { get; set; }
        public string tipo { get; set; }
        public string area { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual EVALUACION_PRODUCTIVA EVALUACION_PRODUCTIVA { get; set; }
    }
}
