//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace adminlte.CPAWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CPAWSSoap", Namespace="http://www.financierasumate.com.mx")]
    public partial class CPAWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WsExecuteProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsExecuteSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsExecuteCPOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsExecuteEstadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsExecuteMunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsExecuteColoniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsGruposClientesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CPAWS() {
            this.Url = global::adminlte.Properties.Settings.Default.adminlte_CPAWS_CPAWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WsExecuteProductosCompletedEventHandler WsExecuteProductosCompleted;
        
        /// <remarks/>
        public event WsExecuteSucursalesCompletedEventHandler WsExecuteSucursalesCompleted;
        
        /// <remarks/>
        public event WsExecuteCPCompletedEventHandler WsExecuteCPCompleted;
        
        /// <remarks/>
        public event WsExecuteEstadosCompletedEventHandler WsExecuteEstadosCompleted;
        
        /// <remarks/>
        public event WsExecuteMunicipiosCompletedEventHandler WsExecuteMunicipiosCompleted;
        
        /// <remarks/>
        public event WsExecuteColoniasCompletedEventHandler WsExecuteColoniasCompleted;
        
        /// <remarks/>
        public event WsGruposClientesCompletedEventHandler WsGruposClientesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteProductos", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteProductos() {
            object[] results = this.Invoke("WsExecuteProductos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteProductosAsync() {
            this.WsExecuteProductosAsync(null);
        }
        
        /// <remarks/>
        public void WsExecuteProductosAsync(object userState) {
            if ((this.WsExecuteProductosOperationCompleted == null)) {
                this.WsExecuteProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteProductosOperationCompleted);
            }
            this.InvokeAsync("WsExecuteProductos", new object[0], this.WsExecuteProductosOperationCompleted, userState);
        }
        
        private void OnWsExecuteProductosOperationCompleted(object arg) {
            if ((this.WsExecuteProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteProductosCompleted(this, new WsExecuteProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteSucursales", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteSucursales() {
            object[] results = this.Invoke("WsExecuteSucursales", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteSucursalesAsync() {
            this.WsExecuteSucursalesAsync(null);
        }
        
        /// <remarks/>
        public void WsExecuteSucursalesAsync(object userState) {
            if ((this.WsExecuteSucursalesOperationCompleted == null)) {
                this.WsExecuteSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteSucursalesOperationCompleted);
            }
            this.InvokeAsync("WsExecuteSucursales", new object[0], this.WsExecuteSucursalesOperationCompleted, userState);
        }
        
        private void OnWsExecuteSucursalesOperationCompleted(object arg) {
            if ((this.WsExecuteSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteSucursalesCompleted(this, new WsExecuteSucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteCP", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteCP(int nCP) {
            object[] results = this.Invoke("WsExecuteCP", new object[] {
                        nCP});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteCPAsync(int nCP) {
            this.WsExecuteCPAsync(nCP, null);
        }
        
        /// <remarks/>
        public void WsExecuteCPAsync(int nCP, object userState) {
            if ((this.WsExecuteCPOperationCompleted == null)) {
                this.WsExecuteCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteCPOperationCompleted);
            }
            this.InvokeAsync("WsExecuteCP", new object[] {
                        nCP}, this.WsExecuteCPOperationCompleted, userState);
        }
        
        private void OnWsExecuteCPOperationCompleted(object arg) {
            if ((this.WsExecuteCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteCPCompleted(this, new WsExecuteCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteEstados", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteEstados() {
            object[] results = this.Invoke("WsExecuteEstados", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteEstadosAsync() {
            this.WsExecuteEstadosAsync(null);
        }
        
        /// <remarks/>
        public void WsExecuteEstadosAsync(object userState) {
            if ((this.WsExecuteEstadosOperationCompleted == null)) {
                this.WsExecuteEstadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteEstadosOperationCompleted);
            }
            this.InvokeAsync("WsExecuteEstados", new object[0], this.WsExecuteEstadosOperationCompleted, userState);
        }
        
        private void OnWsExecuteEstadosOperationCompleted(object arg) {
            if ((this.WsExecuteEstadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteEstadosCompleted(this, new WsExecuteEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteMunicipios", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteMunicipios(int nEstado) {
            object[] results = this.Invoke("WsExecuteMunicipios", new object[] {
                        nEstado});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteMunicipiosAsync(int nEstado) {
            this.WsExecuteMunicipiosAsync(nEstado, null);
        }
        
        /// <remarks/>
        public void WsExecuteMunicipiosAsync(int nEstado, object userState) {
            if ((this.WsExecuteMunicipiosOperationCompleted == null)) {
                this.WsExecuteMunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteMunicipiosOperationCompleted);
            }
            this.InvokeAsync("WsExecuteMunicipios", new object[] {
                        nEstado}, this.WsExecuteMunicipiosOperationCompleted, userState);
        }
        
        private void OnWsExecuteMunicipiosOperationCompleted(object arg) {
            if ((this.WsExecuteMunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteMunicipiosCompleted(this, new WsExecuteMunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsExecuteColonias", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsExecuteColonias(int nEstado, int nMunicipio) {
            object[] results = this.Invoke("WsExecuteColonias", new object[] {
                        nEstado,
                        nMunicipio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsExecuteColoniasAsync(int nEstado, int nMunicipio) {
            this.WsExecuteColoniasAsync(nEstado, nMunicipio, null);
        }
        
        /// <remarks/>
        public void WsExecuteColoniasAsync(int nEstado, int nMunicipio, object userState) {
            if ((this.WsExecuteColoniasOperationCompleted == null)) {
                this.WsExecuteColoniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsExecuteColoniasOperationCompleted);
            }
            this.InvokeAsync("WsExecuteColonias", new object[] {
                        nEstado,
                        nMunicipio}, this.WsExecuteColoniasOperationCompleted, userState);
        }
        
        private void OnWsExecuteColoniasOperationCompleted(object arg) {
            if ((this.WsExecuteColoniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsExecuteColoniasCompleted(this, new WsExecuteColoniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.financierasumate.com.mx/WsGruposClientes", RequestNamespace="http://www.financierasumate.com.mx", ResponseNamespace="http://www.financierasumate.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsGruposClientes(int nCGrupo) {
            object[] results = this.Invoke("WsGruposClientes", new object[] {
                        nCGrupo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsGruposClientesAsync(int nCGrupo) {
            this.WsGruposClientesAsync(nCGrupo, null);
        }
        
        /// <remarks/>
        public void WsGruposClientesAsync(int nCGrupo, object userState) {
            if ((this.WsGruposClientesOperationCompleted == null)) {
                this.WsGruposClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsGruposClientesOperationCompleted);
            }
            this.InvokeAsync("WsGruposClientes", new object[] {
                        nCGrupo}, this.WsGruposClientesOperationCompleted, userState);
        }
        
        private void OnWsGruposClientesOperationCompleted(object arg) {
            if ((this.WsGruposClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsGruposClientesCompleted(this, new WsGruposClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteProductosCompletedEventHandler(object sender, WsExecuteProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteSucursalesCompletedEventHandler(object sender, WsExecuteSucursalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteSucursalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteSucursalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteCPCompletedEventHandler(object sender, WsExecuteCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteEstadosCompletedEventHandler(object sender, WsExecuteEstadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteEstadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteEstadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteMunicipiosCompletedEventHandler(object sender, WsExecuteMunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteMunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteMunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsExecuteColoniasCompletedEventHandler(object sender, WsExecuteColoniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsExecuteColoniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsExecuteColoniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WsGruposClientesCompletedEventHandler(object sender, WsGruposClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsGruposClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsGruposClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591